# Generated by Django 6.0.1 on 2026-02-08 20:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Duplicate of user email for easy access', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('staff_type', models.CharField(choices=[('teacher', 'Teacher'), ('headmaster', 'Headmaster'), ('bursar', 'Bursar'), ('admin_staff', 'Admin Staff'), ('support_staff', 'Support Staff')], max_length=20)),
                ('specialization', models.CharField(blank=True, help_text='Teaching subject/area for teachers', max_length=100)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('health_info', models.TextField(blank=True, help_text='Blood group, allergies, medical conditions')),
                ('photo_url', models.URLField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'staff',
                'db_table': 'staff',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='staff.staff')),
            ],
            options={
                'db_table': 'salary_structures',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_period', models.CharField(help_text="e.g., 'January 2025'", max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_salaries', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='staff.staff')),
            ],
            options={
                'db_table': 'salary_payments',
                'ordering': ['-payment_period'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('annual', 'Annual Leave'), ('maternity', 'Maternity Leave'), ('emergency', 'Emergency Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.staff')),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('half_day', 'Half Day')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_attendance',
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_type'], name='staff_staff_t_63efc1_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['email'], name='staff_email_090e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['staff', 'effective_from'], name='salary_stru_staff_i_dfa32b_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['staff', 'payment_period'], name='salary_paym_staff_i_5ae4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['status'], name='salary_paym_status_b23fa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarypayment',
            unique_together={('staff', 'payment_period')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff', 'status'], name='leave_reque_staff_i_71cf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date'], name='leave_reque_start_d_e77766_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'attendance_date'], name='staff_atten_staff_i_0ec976_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['attendance_date'], name='staff_atten_attenda_ad92ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'attendance_date')},
        ),
    ]
