# Generated by Django 6.0.1 on 2026-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feestructure',
            new_name='fee_structu_academi_fa238e_idx',
            old_name='fee_structu_academi_0ce4e8_idx',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
