# Generated by Django 6.0.1 on 2026-02-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
