# Generated by Django 6.0.1 on 2026-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_fee_structu_academi_0ce4e8_idx_fee_structu_academi_fa238e_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_student_0cbbb5_idx',
            old_name='invoices_student_47f662_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
