# Generated by Django 6.0.1 on 2026-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_invoices_student_47f662_idx_invoices_student_0cbbb5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('utilities', 'Utilities'), ('supplies', 'Supplies'), ('academic', 'academic'), ('maintenance', 'Maintenance'), ('salaries', 'Salaries'), ('transport', 'Transport'), ('other', 'Other')], max_length=20),
        ),
    ]
