# Generated by Django 6.0.1 on 2026-03-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expenditure_category'),
        ('staff', '0002_alter_salarypayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_expenditures', to='staff.staff'),
        ),
    ]
