# Generated by Django 6.0.1 on 2026-02-15 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(help_text='Student member who registered this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('half_day', 'Half Day')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_logs', to='students.student')),
            ],
            options={
                'db_table': 'Student_attendance',
                'ordering': ['-attendance_date'],
                'indexes': [models.Index(fields=['student', 'attendance_date'], name='Student_att_student_aed9e2_idx'), models.Index(fields=['attendance_date'], name='Student_att_attenda_b3857c_idx')],
                'unique_together': {('student', 'attendance_date')},
            },
        ),
    ]
