# Generated by Django 6.0.1 on 2026-02-19 10:09

import apps.students.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_created_by_studentattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.students.models._generate_code, max_length=12, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=apps.students.models._default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parent_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='student_att_student_976455_idx',
            old_name='Student_att_student_aed9e2_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='student_att_attenda_fc169a_idx',
            old_name='Student_att_attenda_b3857c_idx',
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to User account for app access. Leave blank until access is granted.', limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='can_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='is_primary_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='studentattendance',
            table='student_attendance',
        ),
        migrations.AddField(
            model_name='parentinvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentinvite',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='students.parent'),
        ),
    ]
