# Generated by Django 6.0.1 on 2026-02-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('topic_title', models.CharField(max_length=255)),
                ('content_summary', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academic.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='teachers.teacher')),
            ],
            options={
                'verbose_name_plural': 'syllabi',
                'db_table': 'syllabus',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, default='', max_length=50)),
                ('academic_year', models.CharField(blank=True, default='', max_length=50)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(max_length=20)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academic.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academic.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teachers.teacher')),
            ],
            options={
                'db_table': 'timetable',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'day_of_week', 'start_time', 'end_time', 'term', 'academic_year'), name='unique_teacher_schedule')],
            },
        ),
    ]
