# Generated by Django 6.0.1 on 2026-02-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rename_classes_academi_c56e9f_idx_classes_academi_fdbba0_idx_and_more'),
        ('teachers', '0003_alter_teacher_created_at_alter_teacher_date_joined'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Timetable entry', 'verbose_name_plural': 'Timetable entries'},
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_teacher_schedule',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='academic_year',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='term',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['class_obj', 'term', 'academic_year'], name='timetable_class_i_ede2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'term', 'academic_year'], name='timetable_teacher_d1155e_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['term', 'academic_year'], name='timetable_term_a84b10_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='timetable_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('class_obj', 'subject', 'day_of_week', 'start_time', 'end_time', 'term', 'academic_year'), name='unique_class_subject_exact_timeslot'),
        ),
    ]
