# Generated by Django 6.0.1 on 2026-05-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_status', models.CharField(choices=[('alive', 'Alive'), ('deceased', 'Deceased'), ('unknown', 'Unknown')], default='alive', max_length=20)),
                ('father_status', models.CharField(choices=[('alive', 'Alive'), ('deceased', 'Deceased'), ('unknown', 'Unknown')], default='alive', max_length=20)),
                ('parents_relationship_status', models.CharField(blank=True, choices=[('living_together', 'Living Together'), ('separated', 'Separated'), ('divorced', 'Divorced')], max_length=30, null=True)),
                ('fees_payer_title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=10, null=True)),
                ('fees_payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fees_payer_address', models.TextField(blank=True, null=True)),
                ('fees_payer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fees_payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fees_payer_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('male_guardian_title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=10, null=True)),
                ('male_guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('male_guardian_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('male_guardian_address', models.TextField(blank=True, null=True)),
                ('male_guardian_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('male_guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('female_guardian_title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=10, null=True)),
                ('female_guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('female_guardian_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('female_guardian_address', models.TextField(blank=True, null=True)),
                ('female_guardian_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('female_guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('has_normal_health', models.BooleanField(default=True)),
                ('health_condition_details', models.TextField(blank=True, null=True)),
                ('has_normal_hearing', models.BooleanField(default=True)),
                ('hearing_condition_details', models.TextField(blank=True, null=True)),
                ('other_health_information', models.TextField(blank=True, null=True)),
                ('adjustment_and_cooperation', models.TextField(blank=True, null=True)),
                ('attitude_description', models.TextField(blank=True, null=True)),
                ('has_psychological_trauma', models.BooleanField(default=False)),
                ('psychological_trauma_details', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('office_in_charge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('office_date', models.DateField(blank=True, null=True)),
                ('approval', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'db_table': 'admission',
                'ordering': ['-created_at'],
            },
        ),
    ]
