# Generated by Django 6.0.1 on 2026-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='office_in_charge_name',
            field=models.CharField(blank=True, default='admin', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='office_signature',
            field=models.CharField(blank=True, default='admin', max_length=255, null=True),
        ),
    ]
