# Generated by Django 6.0.1 on 2026-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admission_office_in_charge_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
