# Generated by Django 6.0.1 on 2026-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('console', 'Console'), ('smtp', 'SMTP')], default='console', max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('host_user', models.CharField(blank=True, max_length=255)),
                ('host_password', models.CharField(blank=True, max_length=255)),
                ('default_from_email', models.CharField(blank=True, max_length=255)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
