# Generated by Django 6.0.1 on 2026-02-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(help_text="e.g., '2024/2025'", max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['year_name'], name='academic_ye_year_na_e46bac_idx'), models.Index(fields=['is_current'], name='academic_ye_is_curr_307122_idx')],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text="e.g., 'Grade 5A'", max_length=50)),
                ('grade_level', models.IntegerField(help_text='1-12 or your grading system')),
                ('section', models.CharField(blank=True, help_text='A, B, C, etc.', max_length=10)),
                ('capacity', models.IntegerField(default=40)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'classes',
                'db_table': 'classes',
                'ordering': ['grade_level', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('roll_number', models.IntegerField(blank=True, help_text='Position in class', null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.IntegerField(blank=True, help_text='Which grade this subject is for (optional)', null=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['subject_code'],
                'indexes': [models.Index(fields=['subject_code'], name='subjects_subject_e16b01_idx'), models.Index(fields=['grade_level'], name='subjects_grade_l_ca2342_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academic.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='staff.staff')),
            ],
            options={
                'db_table': 'subject_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year'], name='classes_academi_c56e9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_name', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollments_student_379f04_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_obj'], name='enrollments_class_o_d43675_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollments_status_dfab18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_obj')},
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['teacher'], name='subject_ass_teacher_424daf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('class_obj', 'subject')},
        ),
    ]
