# Generated by Django 6.0.1 on 2026-02-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_code'], name='subjects_subject_e16b01_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['grade_level'], name='subjects_grade_l_ca2342_idx'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.class'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='staff.staff'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year'], name='classes_academi_c56e9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_name', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollments_student_379f04_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_obj'], name='enrollments_class_o_d43675_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollments_status_dfab18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_obj')},
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['teacher'], name='subject_ass_teacher_424daf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('class_obj', 'subject')},
        ),
    ]
