# Generated by Django 6.0.1 on 2026-02-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='class',
            new_name='classes_academi_fdbba0_idx',
            old_name='classes_academi_c56e9f_idx',
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(blank=True, help_text='2025-2026', max_length=10),
        ),
    ]
