# Generated by Django 6.0.1 on 2026-02-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rename_classes_academi_c56e9f_idx_classes_academi_fdbba0_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade_level', 'section', 'academic_year')},
        ),
    ]
