# Generated by Django 6.0.1 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_class_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(blank=True, related_name="classes", to="academic.subject"),
        ),
    ]
