# Generated by Django 6.0.1 on 2026-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_class_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(blank=True, db_index=True, help_text="e.g. '2024-2025'", max_length=20),
        ),
    ]
