# Generated by Django 6.0.1 on 2026-03-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_enrollment_academic_year'),
        ('students', '0003_parentinvite_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_obj', 'academic_year')},
        ),
    ]
