# Generated by Django 6.0.1 on 2026-03-02 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_parentinvite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('from_class', models.CharField(max_length=50)),
                ('to_class', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('promoted', 'Promoted'), ('demoted', 'Demoted'), ('graduated', 'Graduated'), ('withheld', 'Withheld')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrollment_applied', models.BooleanField(default=False, help_text='True once apply_to_enrollment() has been successfully run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='students.student')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
