# Generated by Django 6.0.1 on 2026-03-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentManager', '0001_initial'),
        ('students', '0003_parentinvite_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogression',
            unique_together={('student', 'academic_year', 'from_class')},
        ),
    ]
