# Generated by Django 6.0.1 on 2026-02-03 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], db_index=True, default='first', max_length=10)),
                ('grade_type', models.CharField(blank=True, choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('project', 'Project')], max_length=20)),
                ('grade_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('assessment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assessment_total', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('test_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('test_total', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_total', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('weighted_assessment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weighted_test', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weighted_exam', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade_letter', models.CharField(blank=True, max_length=2)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_grades', to='academic.class')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_grades', to='academic.enrollment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_grades', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_grades', to='academic.subject')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-grade_date'],
                'indexes': [models.Index(fields=['student', 'subject'], name='grades_student_f99f41_idx'), models.Index(fields=['term', 'academic_year'], name='grades_term_309350_idx')],
                'unique_together': {('student', 'class_obj', 'subject', 'academic_year', 'term')},
            },
        ),
    ]
