# Generated by Django 6.0.1 on 2026-02-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_options_teacher_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
